spring:
  application:
    name: spring-boot
  datasource:
    url: jdbc:postgresql://localhost:5332/kariioke
    username: kariioke
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: 